#!/usr/bin/env bash

BASE_DIR="$(dirname $(cd "$(dirname "$0")" && pwd))"
PKG_NAME=$(basename $BASE_DIR)
CONTAINER_DIR=$(dirname $BASE_DIR)
APP_DIR=$(dirname $CONTAINER_DIR)

if [ $(basename $CONTAINER_DIR) == "node_modules" ] && [ -d $APP_DIR/sugly/modules ]; then
  ln -s $BASE_DIR/sugly $APP_DIR/sugly/modules/$PKG_NAME
fi
